global:
  backgroundColor: "#0F172A"
  contrastBackgroundColor: "#1E293B"
  moreContrastBackgroundColor: "#387D44"
  textColor: "#E2E8F0"
  secondaryTextColor: "#FDE68A"
  borderColor: "#387D44"
  focusColor: "#4ADE80"
  titleColor: "#387D44"
  graphicsColor: "#387D44"
welcome:
  textColor: "#FDE68A"
  formLabelColor: "#FDE68A"
  formInputColor: "#E2E8F0"
  formInputBackgroundColor: "#1E293B"
connection:
  formLabelColor: "#F1FA8C"
  formInputBackgroundColor: "#163694"
  formInputColor: "#F1FA8C"
  formButtonColor: "#387D44"
  listTextColor: "#F1FA8C"
  listSelectedTextColor: "#F1FA8C"
  listSelectedBackgroundColor: "#387D44"
  listSecondaryTextColor: "#387D44"
  listSecondaryBackgroundColor: "#0F172A"
header:
  keyColor: "#FDE68A"
  valueColor: "#387D44"
  activeSymbol: ●
  inactiveSymbol: ○
databases:
  nodeTextColor: "#387D44"
  leafTextColor: "#E2E8F0"
  nodeSymbolColor: "#FDE68A"
  leafSymbolColor: "#387D44"
  openNodeSymbol: "\U0001F5C1"
  closedNodeSymbol: "\U0001F5BF"
  leafSymbol: "\U0001F5CE"
content:
  docInfoTextColor: "#FDE68A"
  headerRowColor: "#1E293B"
  columnKeyColor: "#FDE68A"
  columnTypeColor: "#387D44"
  cellTextColor: "#387D44"
  activeRowColor: "#4ADE80"
  selectedRowColor: "#4ADE80"
  separatorSymbol: "|"
  separatorColor: "#334155"
docPeeker:
  keyColor: "#387D44"
  valueColor: "#E2E8F0"
  bracketColor: "#FDE68A"
  highlightColor: "#3a4963"
filterBar:
  labelColor: "#FDE68A"
  inputColor: "#E2E8F0"
  autocomplete:
    backgroundColor: "#1E293B"
    textColor: "#E2E8F0"
    activeBackgroundColor: "#387D44"
    activeTextColor: "#0F172A"
    secondaryTextColor: "#FDE68A"
history:
  textColor: "#E2E8F0"
  selectedTextColor: "#0F172A"
  selectedBackgroundColor: "#387D44"
help:
  headerColor: "#387D44"
  keyColor: "#FDE68A"
  descriptionColor: "#E2E8F0"
others:
  buttonsTextColor: "#FDE68A"
  buttonsBackgroundColor: "#387D44"
  deleteButtonSelectedBackgroundColor: "#DA3312"
  modalTextColor: "#FDE68A"
  modalSecondaryTextColor: "#387D44"
styleChange:
  textColor: "#E2E8F0"
  selectedTextColor: "#0F172A"
  selectedBackgroundColor: "#387D44"
