project_name: vi-mongo
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/kopecmaciej/vi-mongo/cmd.version={{.Tag}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip

changelog:
  use: github
  format: |
    # {{ .Tag }} ({{ .CommitDate }})

    🚀 **What's New**

    This release brings enhancements, bug fixes, and more!

    {{ if .Prerelease }}
    ## 🚧 Alpha Release
    {{ end }}

    {{ range .Commits -}}
    {{ if (contains .Message "feat:") }}
    ### 🎉 New Features
    - {{ .Message | trimprefix "feat:" | trim }}
    {{ end }}
    {{ end }}

    {{ range .Commits -}}
    {{ if (contains .Message "fix:") }}
    ### 🐛 Bug Fixes
    - {{ .Message | trimprefix "fix:" | trim }}
    {{ end }}
    {{ end }}

    {{ range .Commits -}}
    {{ if or (contains .Message "chore:") (contains .Message "refactor:") }}
    ### 🔧 Maintenance
    - {{ .Message | trim }}
    {{ end }}
    {{ end }}

release:
  github:
    owner: kopecmaciej
    name: vi-mongo

  # for now it will be a pre-release
  prerelease: true

checksum:
  name_template: "{{ .ProjectName }}_checksum_sha256.txt"
